# Generated by Django 6.0.7 on 2026-07-09 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=100)),
                ('telefono_cliente', models.CharField(blank=True, max_length=20, null=True)),
                ('tipo_entrega', models.CharField(choices=[('delivery', 'Delivery'), ('retiro_tienda', 'Retiro en tienda')], default='delivery', max_length=30)),
                ('detalle_entrega', models.CharField(blank=True, help_text='Dirección para delivery o referencia para retiro', max_length=200, null=True)),
                ('pedido', models.TextField()),
                ('monto', models.PositiveIntegerField()),
                ('tipo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('debito', 'Débito'), ('credito', 'Crédito'), ('otro', 'Otro')], default='efectivo', max_length=30)),
                ('estado_pago', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado')], default='pendiente', max_length=30)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagos.vendedor')),
            ],
        ),
    ]
