# Generated by Django 6.0.7 on 2026-07-09 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='estado_pedido',
            field=models.CharField(choices=[('recibido', 'Recibido'), ('preparando', 'Preparando'), ('listo', 'Listo'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='recibido', max_length=30),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='detalle_entrega',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='telefono_cliente',
            field=models.CharField(default='00000000', max_length=20),
            preserve_default=False,
        ),
    ]
