# Generated by Django 6.0.7 on 2026-07-24 19:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0004_vendedor_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedido',
            options={'ordering': ['-fecha']},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado_pago',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado')], db_index=True, default='pendiente', max_length=30),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado_pedido',
            field=models.CharField(choices=[('recibido', 'Recibido'), ('preparando', 'Preparando'), ('listo', 'Listo'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], db_index=True, default='recibido', max_length=30),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='monto',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='nombre_cliente',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='telefono_cliente',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='tipo_entrega',
            field=models.CharField(choices=[('delivery', 'Delivery'), ('retiro_tienda', 'Retiro en tienda')], db_index=True, default='delivery', max_length=30),
        ),
        migrations.AlterField(
            model_name='producto',
            name='activo',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(db_index=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='nombre',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='detallepedido',
            index=models.Index(fields=['pedido'], name='pagos_detal_pedido__4c1029_idx'),
        ),
        migrations.AddIndex(
            model_name='detallepedido',
            index=models.Index(fields=['producto'], name='pagos_detal_product_3bfd4f_idx'),
        ),
        migrations.AddIndex(
            model_name='detallepedido',
            index=models.Index(fields=['pedido', 'producto'], name='pagos_detal_pedido__a589c6_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['fecha'], name='pagos_pedid_fecha_1625b1_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['vendedor', 'fecha'], name='pagos_pedid_vendedo_7eed70_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['tipo_entrega', 'fecha'], name='pagos_pedid_tipo_en_e701be_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['estado_pago', 'fecha'], name='pagos_pedid_estado__fd57ad_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['estado_pedido', 'fecha'], name='pagos_pedid_estado__6d38a6_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['nombre_cliente'], name='pagos_pedid_nombre__874930_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['telefono_cliente'], name='pagos_pedid_telefon_926faf_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['monto'], name='pagos_pedid_monto_00c548_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['nombre'], name='pagos_produ_nombre_410d04_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['activo'], name='pagos_produ_activo_c1f08c_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['activo', 'nombre'], name='pagos_produ_activo_ce3a8f_idx'),
        ),
        migrations.AddIndex(
            model_name='vendedor',
            index=models.Index(fields=['nombre'], name='pagos_vende_nombre_d43cb5_idx'),
        ),
    ]
