# Generated by Django 6.0.7 on 2026-07-26 04:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0005_alter_pedido_options_alter_producto_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Negocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_index=True, max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('direccion', models.CharField(blank=True, max_length=250, null=True)),
                ('activo', models.BooleanField(db_index=True, default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nombre'],
                'indexes': [models.Index(fields=['nombre'], name='pagos_negoc_nombre_be7597_idx'), models.Index(fields=['activo'], name='pagos_negoc_activo_6da9f9_idx'), models.Index(fields=['slug'], name='pagos_negoc_slug_940bf1_idx')],
            },
        ),
        migrations.CreateModel(
            name='DuenoNegocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(db_index=True, default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_dueno', to=settings.AUTH_USER_MODEL)),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duenos', to='pagos.negocio')),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='negocio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='pagos.negocio'),
        ),
        migrations.AddField(
            model_name='producto',
            name='negocio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='pagos.negocio'),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='negocio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendedores', to='pagos.negocio'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['negocio'], name='pagos_pedid_negocio_f98ed4_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['negocio', 'fecha'], name='pagos_pedid_negocio_74ad4a_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['negocio', 'tipo_entrega', 'fecha'], name='pagos_pedid_negocio_a99499_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['negocio', 'estado_pago', 'fecha'], name='pagos_pedid_negocio_465a56_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['negocio'], name='pagos_produ_negocio_6a7239_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['negocio', 'activo'], name='pagos_produ_negocio_634e7c_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['negocio', 'nombre'], name='pagos_produ_negocio_343906_idx'),
        ),
        migrations.AddIndex(
            model_name='vendedor',
            index=models.Index(fields=['negocio'], name='pagos_vende_negocio_260d3f_idx'),
        ),
        migrations.AddIndex(
            model_name='vendedor',
            index=models.Index(fields=['negocio', 'nombre'], name='pagos_vende_negocio_e18061_idx'),
        ),
        migrations.AddIndex(
            model_name='duenonegocio',
            index=models.Index(fields=['negocio'], name='pagos_dueno_negocio_37c6fb_idx'),
        ),
        migrations.AddIndex(
            model_name='duenonegocio',
            index=models.Index(fields=['activo'], name='pagos_dueno_activo_7f3d81_idx'),
        ),
    ]
